services:

  #
  # Page renderer
  #
  beloop.typeform.page_renderer:
      class: Beloop\Component\Typeform\Services\PageRenderer
      arguments:
          - '@logger'
          - '@session'
          - '@guzzle.client.api_typeform'

  #
  # ScoreRetriever service
  #
  beloop.typeform.score_retriever_service:
      class: Beloop\Component\Typeform\Services\ScoreRetriever
      arguments:
          - '@logger'
          - '@guzzle.client.api_typeform'
          - '%typeform_api_key%'
